### ISSUE TITLE
feature: Add command to generate bash and zsh completion

### ISSUE THREAD

**Issue by at15** [rdelval/australis#4]
The library you are using support generate shell completion script (default is not very smart, just static keywords, you can make it context aware like k8s's)

See https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by rdelval** [comment]
Sorry for the delay, added bash for now. I will tackle zsh if there is a demand for it 😄 

https://github.com/rdelval/australis/commit/2de607464f063f9b06eb41000eb5af282c934e99

Thanks for pointing me to the docs!
